using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Asynchro_Connect.Model
{
    public static class Schools
    {
        public static String[] listOfSchools = {"Athabasca University",
"Concordia University College of Alberta",
"Grant MacEwan University",
"The King's University College",
"Mount Royal University",
"St. Mary's University College",
"University of Alberta",
"Augustana Faculty",
"University of Calgary",
"University of Lethbridge",
"Colleges offering degree programs",
"Alberta College of Art and Design",
"Grande Prairie Regional College",
"Keyano College",
"Lakeland College",
"Lethbridge College",
"Medicine Hat College",
"Northern Alberta Institute of Technology",
"Northern Lakes College",
"Olds College",
"Red Deer College",
"Southern Alberta Institute of Technology",
"Other institutions",
"Alberta Bible College",
"Ambrose College",
"Bow Valley College",
"Canadian University College",
"City University, Calgary location",
"City University, Edmonton location",
"Concordia Lutheran Seminary",
"DeVry Institute of Technology",
"International Biblical Online Leadership Training",
"Loma Linda University, branch campus",
"Newman Theological College",
"Portage College",
"Taylor University College and Seminary",
"University of Phoenix, Calgary campus",
"Robertson College",
"University of British Columbia",
"Simon Fraser University",
"Kwantlen Polytechnic University",
"Royal Roads University",
"University of Northern British Columbia",
"Emily Carr University of Art and Design",
"Thompson Rivers University",
"Trinity Western University",
"University of the Fraser Valley",
"Vancouver Island University (formerly Malaspina)",
"University of Victoria",
"British Columbia Institute of Technology",
"Capilano University",
"Century College of Art and Business",
"City University, Vancouver location",
"City University, Victoria location",
"College of the Rockies",
"Fairleigh Dickinson University, Vancouver campus",
"Institute of Indigenous Government (now part of NVIT)",
"Nicola Valley Institute of Technology",
"Quest University Canada",
"Seminary of Christ the King",
"Sprott-Shaw Community College",
"Associated Canadian Theological Schools",
"University Canada West",
"Regent College",
"University of Phoenix, Vancouver campus",
"Vancouver School of Theology",
"Colleges with university transfer courses:",
"Camosun College",
"Columbia College",
"Coquitlam College",
"Douglas College",
"Langara College",
"North Island College",
"Northern Lights College",
"Okanagan College",
"Selkirk College",
"Booth College",
"Brandon University",
"Canadian Mennonite University",
"Menno Simons College",
"Providence College and Theological Seminary",
"University College of the North",
"University of Manitoba",
"Collège de St.-Boniface",
"St. John's College",
"St. Paul's College",
"University of Winnipeg",
"Robertson College",
"Bethany College",
"Crandall University (Atlantic Baptist University)",
"Meritus University",
"Mount Allison University",
"St. Stephen's University",
"Saint Thomas University",
"Université de Moncton",
"Shippagan campus",
"Edmundston (Saint-Louis-Maillet)",
"University of Fredericton",
"University of New Brunswick, Fredericton and Saint John",
"Yorkville University",
"Memorial University of Newfoundland",
"Grenfell Campus",
"Aurora College",
"Acadia University",
"Acadia Divinity College",
"Atlantic School of Theology",
"Cape Breton University",
"Dalhousie University",
"Mount St. Vincent University",
"Nova Scotia Agricultural College",
"NSCAD University (formerly Nova Scotia College of Art and Design)",
"St. Francis Xavier University",
"Saint Mary's University",
"Université Sainte-Anne",
"University of King's College",
"Nunavut Arctic College",
"Maritime Christian College",
"University of Prince Edward Island",
"Algoma University",
"Brock University",
"Carleton University",
"College Dominicain",
"Charles Sturt University, Ontario",
"Lakehead University",
"Laurentian University",
"Huntington University",
"Thorneloe University",
"Université de Hearst",
"University of Sudbury",
"McMaster University",
"Nipissing University",
"OCAD University (Ontario College of Art and Design)",
"Queen's University",
"Royal Military College of Canada",
"Ryerson University",
"Trent University",
"University of Guelph",
"University of Guelph-Humber",
"University of Ontario Institute of Technology",
"University of Ottawa",
"Saint Paul University",
"University of Toronto",
"Ontario Institute for Studies in Education (OISE)",
"St. Michael's College",
"Trinity College",
"Victoria University, including Emmanuel College",
"University of Waterloo",
"St. Jerome's University",
"St. Paul's University College",
"University of Western Ontario",
"Huron College",
"University of Windsor",
"Assumption University",
"Wilfrid Laurier University",
"York University",
"Colleges of Applied Arts and Technology offering degree programs",
"Algonquin College",
"Centennial College",
"Conestoga College",
"Confederation College",
"Fanshawe College",
"Fleming College",
"George Brown College",
"Georgian College",
"Humber College",
"La Cité Collégiale",
"Lambton College",
"Loyalist College",
"Mohawk College",
"Niagara College",
"St. Clair College",
"St. Lawrence College",
"Seneca College",
"Sheridan College",
"Adler Graduate School of Ontario, Inc.",
"Canadian College of Naturopathic Medicine",
"Canadian Memorial Chiropractic College",
"Emmanuel Bible College",
"Heritage College and Seminary",
"Institute for Christian Studies",
"Master's College and Seminary",
"Michener Institute for Applied Health Sciences",
"RCC Institute of Technology",
"Redeemer University College",
"Tyndale University College and Seminary",
"Westervelt College",
"Bishop's University",
"Concordia University",
"Ecole Polytechnique",
"HEC (Ecole des Hautes Etudes Commerciales) Montréal",
"McGill University",
"Université de Montréal",
"Université du Québec, central",
"Ecole Nationale d'Administration Publique",
"Ecole de Technologie Superieure",
"Institut Armand-Frappier",
"Institut National de la Récherche Scientifique",
"Télé-Université",
"Université du Québec Ã  Abitibi-Temiscamingue",
"Université du Québec Ã  Chicoutimi",
"Université du Québec Ã  Montréal",
"Université du Québec Ã  Rimouski",
"Université du Québec Ã  Trois-Rivières",
"Université du Québec en Outaouais",
"Université de Sherbrooke",
"Université Laval",
"Bethany Bible Institute",
"Briercrest College and Seminary",
"Eston College",
"First Nations University of Canada",
"Fountain of Life School of Ministry",
"University of Regina",
"Campion College",
"Luther College",
"University of Saskatchewan",
"Saskatoon Theological Union",
"St. Peter's College",
"St. Thomas More College",
 };
    }
}
